name: GPS Data Collection

on:
  schedule:
    - cron: '*/7 * * * *' # Runs every 7 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  collect-gps:
    name: Collect GPS Data
    runs-on: ubuntu-latest

    steps:
      - name: Check Environment
        run: |
          echo "🔍 Checking configuration..."
          echo "APP_URL is set: ${{ secrets.APP_URL != '' }}"
          echo "CRON_SECRET is set: ${{ secrets.CRON_SECRET != '' }}"
          echo "Target URL: ${{ secrets.APP_URL }}/api/gps/batch"

      - name: Call GPS Batch Endpoint
        run: |
          echo "🚀 Making API request..."

          # Make request and capture full output
          RESPONSE=$(curl -v -s -w "\n%{http_code}" \
            -X GET \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.APP_URL }}/api/gps/batch" 2>&1)

          echo "📝 Full response:"
          echo "$RESPONSE"

          # Extract status code
          STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
          echo "📡 Status code: $STATUS_CODE"

          if [ "$STATUS_CODE" -ge 400 ]; then
            echo "❌ Request failed with status $STATUS_CODE"
            exit 1
          fi

      - name: Log Completion
        if: always()
        run: |
          echo "⏱️ Job completed at $(date)"
          echo "Final status: ${{ job.status }}"
