name: GPS Data Collector

on:
  schedule:
    # Run every 7 minutes
    - cron: '*/7 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  collect-gps-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Call GPS Batch API
        run: |
          curl -X GET "${{ secrets.APP_URL }}/api/gps/batch" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          COMPASS_CLIENT_ID: ${{ secrets.COMPASS_CLIENT_ID }}
          COMPASS_CLIENT_SECRET: ${{ secrets.COMPASS_CLIENT_SECRET }}
